///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestTemplate
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RestartSystemX recording.
    /// </summary>
    [TestModule("ff4d5af6-2089-4ec2-be57-1342eede460b", ModuleType.Recording, 1)]
    public partial class RestartSystemX : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SXRepos repository.
        /// </summary>
        public static SXRepos repo = SXRepos.Instance;

        static RestartSystemX instance = new RestartSystemX();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RestartSystemX()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RestartSystemX Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Kill System X process
            Report.Log(ReportLevel.Info, "Application", "Kill System X process\r\nClosing application containing item 'frmStartmeny'.", repo.frmStartmeny.SelfInfo, new RecordItemIndex(0));
            Host.Current.CloseApplication(repo.frmStartmeny.Self, new Duration(0));
            Delay.Milliseconds(0);
            
            // Start System X
            Report.Log(ReportLevel.Info, "Application", "Start System X\r\nRun application 'C:\\HMSCLIENT\\Systemx.exe' with arguments '' in normal mode.", new RecordItemIndex(1));
            Host.Local.RunApplication("C:\\HMSCLIENT\\Systemx.exe", "", "C:\\HMSCLIENT", false);
            Delay.Milliseconds(0);
            
            SXNamespace.SXCollections.SXAutoLogin();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
