///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SystemXTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SystemXAuto_Test element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("c8bee4f4-62d8-43b2-b573-ac82847444df")]
    public partial class SystemXAuto_Test : RepoGenBaseFolder
    {
        static SystemXAuto_Test instance = new SystemXAuto_Test();

        /// <summary>
        /// Gets the singleton class instance representing the SystemXAuto_Test element repository.
        /// </summary>
        [RepositoryFolder("c8bee4f4-62d8-43b2-b573-ac82847444df")]
        public static SystemXAuto_Test Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SystemXAuto_Test() 
            : base("SystemXAuto_Test", "/", null, 0, false, "c8bee4f4-62d8-43b2-b573-ac82847444df", ".\\RepositoryImages\\SystemXAuto_Testc8bee4f4.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c8bee4f4-62d8-43b2-b573-ac82847444df")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class SystemXAuto_TestFolders
    {
    }
#pragma warning restore 0436
}