///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SXAutoLibs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SXAutoLibsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("51712d55-9476-4045-93b1-cebe77c922fd")]
    public partial class SXAutoLibsRepository : RepoGenBaseFolder
    {
        static SXAutoLibsRepository instance = new SXAutoLibsRepository();

        /// <summary>
        /// Gets the singleton class instance representing the SXAutoLibsRepository element repository.
        /// </summary>
        [RepositoryFolder("51712d55-9476-4045-93b1-cebe77c922fd")]
        public static SXAutoLibsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SXAutoLibsRepository() 
            : base("SXAutoLibsRepository", "/", null, 0, false, "51712d55-9476-4045-93b1-cebe77c922fd", ".\\RepositoryImages\\SXAutoLibsRepository51712d55.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("51712d55-9476-4045-93b1-cebe77c922fd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class SXAutoLibsRepositoryFolders
    {
    }
#pragma warning restore 0436
}